sudo: required
services:
  - docker

before_install:
  - docker build -t tina/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tina/docker-react npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  access_key_id: AWS_ACCESS_KEY
  secret_access_key: AWS_SECRET_KEY
  region: 'us-east-2'
  app: 'docker-react'
  env: 'DockerReact-env'
  bucket_name: 'elasticbeanstalk-us-east-2-012734556430'
  bucket_path: 'docker-react'
  on:
    branch: master
